name: "spot_draws_gcode"

services:
  automation:
    build:
      dockerfile: ./automation/api/Dockerfile
    command: flask run --with-threads --host 0.0.0.0 --port 8080
    # command: tail -f /dev/null
    ports:
      - 8080:8080
    working_dir: /app/
    volumes:
      - ./automation/api:/app
    environment:
      - SDK_NAME=SpotDrawsGcodeSDK
      - ROBOT_IP=192.168.80.3
      - BOSDYN_CLIENT_USERNAME=${BOSDYN_CLIENT_USERNAME}
      - BOSDYN_CLIENT_PASSWORD=${BOSDYN_CLIENT_PASSWORD}
      - FLASK_DEBUG=True
      - FLASK_APP=main.py
